// Generated by CoffeeScript 1.6.2
(function() {
  var app, config, http, router;

  config = require('./configuration');

  router = require('./router');

  http = require('http');

  app = config.configure();

  router.route(app);

  setTimeout((function() {
    return console.log("fooo" + process.env.steamAPIkey);
  }), 2000)();

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + app.get('port'));
  });

}).call(this);
